### PR TITLE
CI: Add macos-14

### PR DESCRIPTION
**Pull request by andy5995**
Part of https://github.com/KaruroChori/vs-fltk/issues/9

### CODE REVIEW

**Comment by andy5995** [comment]
I don't know yet this is failing. It looks to me like it's detecting clang, but it's not detecting *all* of clang:

```
Homebrew clang version 19.1.4
  Target: arm64-apple-darwin23.6.0
  Thread model: posix
  InstalledDir: /opt/homebrew/Cellar/llvm/19.1.4/bin
  Configuration file: /opt/homebrew/etc/clang/arm64-apple-darwin23.cfg
  -----------
  Running command: -x c -E -dM -
  -----
  -----------
  Detecting linker via: `clang-19 -Wl,--version -L/opt/homebrew/opt/llvm/lib -I/opt/homebrew/opt/llvm/include` -> 1
  stderr:
  ld: unknown options: --version 
  clang-19: error: linker command failed with exit code 1 (use -v to see invocation)
  -----------
  -----------
  Detecting Apple linker via: `clang-19 -Wl,-v -L/opt/homebrew/opt/llvm/lib -I/opt/homebrew/opt/llvm/include` -> 0
  stderr:
  @(#)PROGRAM:ld PROJECT:ld-1053.12
  BUILD 10:15:51 Mar 29 2024
  configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
  will use ld-classic for: armv6 armv7 armv7s arm64_32 i386 armv6m armv7k armv7m armv7em
  LTO support using: LLVM version 19.1.4 (static support for 29, runtime is 29)
  TAPI support using: Apple TAPI version 15.0.0 (tapi-1500.3.2.2)
  -----------
  Sanity testing C compiler: clang-19
  Is cross compiler: False.
  Sanity check compiler command line: clang-19 sanitycheckc.c -o sanitycheckc.exe -I/opt/homebrew/opt/llvm/include -L/opt/homebrew/opt/llvm/lib
  Sanity check compile stdout:
  
  -----
  Sanity check compile stderr:
  
  -----
  Running test binary command:  /Users/runner/work/vs-fltk/vs-fltk/build/meson-private/sanitycheckc.exe
  C compiler for the host machine: clang-19 (clang 19.1.4 "Homebrew clang version 19.1.4")
  C linker for the host machine: clang-19 ld64 1053.12
  -----------
  Detecting archiver via: `llvm-ar-19 --version` -> [Errno 2] No such file or directory: 'llvm-ar-19'
  -----------
  Detecting archiver via: `llvm-ar --version` -> 0
  stdout:
  Homebrew LLVM version 19.1.4
    Optimized build.
  -----------
  -----------
  Detecting compiler via: `clang++-19 --version` -> [Errno 2] No such file or directory: 'clang++-19'
  
  meson.build:1:0: ERROR: Unknown compiler(s): [['clang++-19']]
  The following exception(s) were encountered:
  Running `clang++-19 --version` gave "[Errno 2] No such file or directory: 'clang++-19'"
```

**Comment by KaruroChori** [comment]
It can just be that clang++ is an optional component, so the C++ runtime and compiler are shipped in a different homebrew packaged.

**Comment by andy5995** [comment]
I think it's all together. Here it is some info about the package on the brew site: https://formulae.brew.sh/formula/llvm#default

**Comment by andy5995** [comment]
Adding the symlink worked. I tried that because I noticed on my Manjaro system there's a _clang-18_ but only a _clang++_ (without the _-18).

**Comment by andy5995** [comment]
Ready for review. Only problem now is the libftlk build fails. On the upstream it does not. https://github.com/fltk/fltk/actions/runs/12087295968/job/33708429921

**Comment by KaruroChori** [comment]
I see. In general, for portability to future versions it would be better to avoid the suffix. So that if 6 months from now clang-20 is out we are good. Could you try using the flatpak.ini profile without links?

**Comment by KaruroChori** [comment]
> Ready for review. Only problem now is the libftlk build fails. On the upstream it does not. https://github.com/fltk/fltk/actions/runs/12087295968/job/33708429921

Ok, I am merging it regardless, as that is probably my problem to fix :D.

**Pull request merged**
