### PR TITLE
Fix MacOS build

### PR DESCRIPTION
**Pull request by andy5995**
For #33

### CODE REVIEW

**Comment by KaruroChori** [comment]
It this works I am going to dance for the next 5 minutes before I fall asleep.

**Comment by KaruroChori** [comment]
No dance, but it is a minor issue now in my own code, just type definition missing as the headers are not really the same between linux and macos.

**Comment by andy5995** [comment]
> No dance, but it is a minor issue now in my own code, just type definition missing as the headers are not really the same between linux and macos. That being said, I would like to understand how is that VERSION made it fail :/. Tomorrow I need to check that one.

ChatGPT said:

>The error you're encountering indicates that clang++ is mistakenly treating the file version in the libtcc directory as a header file during compilation. This likely happens because the compiler attempts to include all files in the include paths, regardless of whether they are source or configuration files

I didn't really buy it, but having no other clues I figured removing VERSION would be worth a try to see if we got different results.

**Comment by KaruroChori** [comment]
Well... the macos task got stuck in a for loop or something like that. I guess we need to set up some reasonable timeout or this is running forever even before it starts compiling.

**Comment by KaruroChori** [comment]
:dancers: !
I am not merging it right away just because I want to investigate that issue with VERSION.  
I don't quite trust the explanation ChatGPT provided on that, I think it is hallucinating too many stars tonight.

**Pull request merged**
